version: "3.1"
services:
  mongo:
    container_name: turingbot-mongo
    image: mongo:3.6.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=turing
      - MONGO_INITDB_ROOT_PASSWORD=turing
    ports:
      - 27017:27017
  api:
    container_name: turingbot-api
    build:
      context: .
      dockerfile: Api.Dockerfile
    env_file: .env
    ports:
      - 3000:8080
  bot:
    container_name: turingbot-bot
    build:
      context: .
      dockerfile: Bot.Dockerfile
    env_file: .env
    ports:
      - 3001:8080
networks:
  default:
    driver: "bridge"
