version: "3.1"
services:
  mongo:
    container_name: turing-mongo-dev
    image: mongo:3.6.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=turing
      - MONGO_INITDB_ROOT_PASSWORD=turing
    ports:
      - "27017:27017"
networks:
  default:
    driver: "bridge"
